export const subjectActionTypes = {
    SEND_CREATE_SUBJECT_REQUEST:"SEND_CREATE_SUBJECT_REQUEST",
    CREATE_SUBJECT_REQUEST_ERROR:"CREATE_SUBJECT_REQUEST_ERROR",
    UPDATE_SUBJECT_LIST:"UPDATE_SUBJECT_LIST",
    FETCH_SUBJECT_LIST:"FETCH_SUBJECT_LIST",
    DELETE_SUBJECT:"DELETE_SUBJECT",

    SELECT_SUBJECT:"SELECT_SUBJECT",
    SET_CURRENT_SUBJECT:"SET_CURRENT_SUBJECT",
    SET_SUBJECT_CONTENT:"SET_SUBJECT_CONTENT",
    SEND_CREATE_BLOG_REQUEST:"SEND_CREATE_BLOG_REQUEST",
    CREATE_BLOG_REQUEST_ERROR:"CREATE_BLOG_REQUEST_ERROR",
    SEND_EDIT_SUBJECT_REQUEST:"SEND_EDIT_SUBJECT_REQUEST",
    EDIT_SUBJECT_REQUEST_ERROR:"EDIT_SUBJECT_REQUEST_ERROR",
    
}