export const userActionTypes = {
    CHECK_ACCESS_TOKEN:"CHECK_ACCESS_TOKEN",
    RENEW_ACCESS_TOKEN:"RENEW_ACCESS_TOKEN",
    UPDATE_USER_INFO:"UPDATE_USER_INFO",
    SEND_LOGIN_REQUEST:"SEND_LOGIN_REQUEST",
    LOGIN_REQUEST_ERROR:"LOGIN_REQUEST_ERROR",
    SEND_REGISTER_REQUEST:"SEND_REGISTER_REQUEST",
    REGISTER_REQUEST_ERROR:"REGISTER_REQUEST_ERROR",
    SET_USER_INFO:"SET_USER_INFO",
    FINISH_ACTION_QUEUE:"FINISH_ACTION_QUEUE",
}